### ISSUE TITLE
Basic items price check is crashing sidekick

### ISSUE THREAD

**Issue by umn-anon** [Sidekick-Poe/Sidekick#101]
When I try to price check (ctrl+d) on scarabs and other fragment types, it always causes an error screen and sidekick is unresponsive afterwards until I exit and restart it. 

https://gyazo.com/c8747dc8fbe6d68597626d3d08c7bba0

Link of example ^^. I'm not sure what the issue is, maybe I need to reinstall it in a new directory? I don't see this issue listed in the recently closed ones or currently open, yet it's a pretty fundamental problem.

**Comment by leMicin** [comment]
Thanks for the report, this is being fixed right now. We should have a patch ready in the next few hours.
