### ISSUE TITLE
No price information for unique items

### ISSUE THREAD

**Issue by KoronGIT** [Sidekick-Poe/Sidekick#118]
Poe Ninja's price information is currently not displayed for unique items.
![pic](https://github.com/Sidekick-Poe/Sidekick/assets/16877169/0e7f4e13-70b9-4d1f-93d5-16a1780ccd9f)

**Comment by leMicin** [comment]
Thanks for the feedback. This is fixed in 2.7.1

**Comment by KoronGIT** [comment]
Was not fixed in 2.7.1. Still no price is displayed.

**Comment by KoronGIT** [comment]
Gegenstandsklasse: Stiefel
Seltenheit: Einzigartig
Shavronnes Hast
Scholarenstiefel
--------
Energieschild: 50 (augmented)
--------
Anforderungen:
Stufe: 50
Str: 48
Ges: 111
Int: 71
--------
Fassungen: B-G B 
--------
Gegenstandsstufe: 35
--------
+26 zu Intelligenz
108% erhöhter Energieschild
15% erhöhte Bewegungsgeschwindigkeit
20% erhöhte Bewegungsgeschwindigkeit bei vollem Leben
197% beschleunigte Betäubungs- und Blockerholung
--------
Shavronne eilte an Brutus' Seite, 
ihre letzte Hoffnung gegen die Karui-Meute.

**Comment by KoronGIT** [comment]
Gegenstandsklasse: Kriegsstäbe
Seltenheit: Einzigartig
Pfeiler des gefangenen Gottes
Eisenstab
--------
Kriegsstab
Physischer Schaden: 14-42
Kritische Trefferchance: 6.40%
Angriffe pro Sekunde: 1.30
Waffenreichweite: 13
--------
Anforderungen:
Stufe: 13
Str: 27
Int: 27
--------
Fassungen: B G 
--------
Gegenstandsstufe: 16
--------
+18% Chance, Angriffsschaden zu blocken beim Tragen eines Stabs (implicit)
--------
1% vergrößerter Wirkungsbereich pro 20 Intelligenz
1% erhöhte Angriffsgeschwindigkeit pro 10 Geschick
16% erhöhter physischer Waffenschaden pro 10 Stärke
--------
Erschaffen, um Wellen und Gezeiten zu beherrschen, 
war es sein Schicksal, des Affen Pfote zu dienen. 
Stark wie ein Turm aus Eisen, geschickt wie eine Nähnadel.

**Comment by KoronGIT** [comment]
Gegenstandsklasse: Zauberstäbe
Seltenheit: Einzigartig
Lebenszweiglein
Treibholz-Zauberstab
--------
Zauberstab
Qualität: +8% (augmented)
Physischer Schaden: 5-10 (augmented)
Kritische Trefferchance: 7.00%
Angriffe pro Sekunde: 1.40
--------
Fassungen: B B 
--------
Gegenstandsstufe: 15
--------
9% erhöhter Zauberschaden (implicit)
--------
+1 zur Stufe eingefasster Zauber-Gemmen
20% erhöhter Zauberschaden
7% erhöhte Zaubergeschwindigkeit
+15 zu maximalem Leben
+18 zu maximalem Mana
Regeneriert 8 Leben im Verlauf 1 Sekunde, wenn Ihr einen Zauber zaubert
--------
Von den kleinsten Samen 
zu den größten Wäldern 
hält das Leben in Wraeclast stand.

**Comment by KoronGIT** [comment]
Gegenstandsklasse: Gürtel
Seltenheit: Einzigartig
Festmahlbinde
Bauernschärpe
--------
Anforderungen:
Stufe: 11
--------
Gegenstandsstufe: 44
--------
23% erhöhter globaler physischer Schaden (implicit)
--------
Fügt Angriffen 5 bis 10 physischen Schaden hinzu
+29 zu maximalem Leben
0.2% des physischen Angriffsschadens werden als Leben geraubt
50% erhöhte Anzahl erhaltener Fläschchenfüllungen während beliebiger Fläschchenwirkung
50% erhöhte Manaregenerations-Rate während beliebiger Fläschchenwirkung
--------
Unsere Ahnen lebten in zügelloser Völlerei
und ehrten die Ersten nicht für ihre Gaben.
So durchzogen die Ersten den Himmel mit Feuer.

**Comment by leMicin** [comment]
You are playing in another language. Poe.ninja API only works in english at the start of the 3.22 league. We have opened a ticket to review their api later in the league to see if they have restored multi language functionality.
