### ISSUE TITLE
please add "only chaos" setting to price checker

### ISSUE THREAD

**Issue by crosscutsaw** [Sidekick-Poe/Sidekick#133]
as title says.

i really don't understand but ppl pricing their items for regal, scour or sextants. i think we really need this setting because finding chaos price is really hard.

image showing i'm trying to get div price
https://i.imgur.com/8k5c6ek.png

**Comment by domialex** [comment]
Until this feature exists, you can use the poe.ninja price shown in the left sidebar. Just make sure you have the latest version installed.

![image](https://github.com/Sidekick-Poe/Sidekick/assets/4694217/4b496c73-f3aa-49e3-8ad9-50a62dbcd2a8)
