### ISSUE TITLE
Is it possible to search how many Currency trades in 1divine

### ISSUE THREAD

**Issue by anigee818** [Sidekick-Poe/Sidekick#142]
I hope it works like this
The rest is very good Thank you.

**Comment by leMicin** [comment]
We are working on the bulk listing feature, so we will be able to do this in a future version :)

**Comment by leMicin** [comment]
This is fixed in #145

**Comment by leMicin** [comment]
It will be part of v2.10 or v3. We are targeting a release for the next league at this point.

**Comment by leMicin** [comment]
This feature will be released today in v2.10

**Comment by anigee818** [comment]
I'm going to use it today 
ty 


-----Original Message-----
