### ISSUE TITLE
whatever I choose its only pricechecking in divines

### ISSUE THREAD

**Issue by SeyShin** [Sidekick-Poe/Sidekick#175]
It doesnt matter what currency I choose when price checking it only shows me divine prices even if there are alot of items for like 10c for sale. Am I missing something or is it buggy for me

**Comment by SeyShin** [comment]
It got fixed with restarting a few times but now the icons for divines or chaos arent showing and I can only guess wich it is

**Comment by leMicin** [comment]
Thanks for the report, this should be fixed in 2.11.3
Let us know if you encounter more issues
