### ISSUE TITLE
latest version, 2.11.3, is being quarantined by crowdstrike falcon

### ISSUE THREAD

**Issue by crosscutsaw** [Sidekick-Poe/Sidekick#178]
hello,

as you can see in images, crowdstrike falcon quarantines the sidekick. there was no problem on latest-1 version.

![11](https://github.com/Sidekick-Poe/Sidekick/assets/73831924/a0e98b83-d0b7-46e2-8563-849a9e57cf8c)
![22](https://github.com/Sidekick-Poe/Sidekick/assets/73831924/f4236840-cea9-4e36-997b-d09ec5cb066e)

i think it's being quarantined because sidekick tries to load ntdll. it makes falcon angry. :))
![33](https://github.com/Sidekick-Poe/Sidekick/assets/73831924/dd6f0c04-3721-4134-b970-56cd6a22088d)

best regards,

**Comment by domialex** [comment]
Nothing's changed in the exe itself since the last version. We'll see if maybe the next generated exe will not trigger this anti-virus.

**Comment by leMicin** [comment]
v3 uses a different engine. Please open a new issue if this occurs in v3.
