### ISSUE TITLE
Closing the overlay sometimes brings up another window instead of POE

### ISSUE THREAD

**Issue by domialex** [Sidekick-Poe/Sidekick#208]

**Comment by Farruh4eg** [comment]
+1.
To reproduce the bug:
1. Price check any item
2. Press space or click close button in the upper right
Congratulations. You just clicked on a window that is "under" poe window

**Comment by leMicin** [comment]
Fixed in #301 . Feel free to reopen or open a ticket if this isn't fixed in the next release
