### ISSUE TITLE
sidekick is not terminating old price check msedgewebview2.exe processes

### ISSUE THREAD

**Issue by crosscutsaw** [Sidekick-Poe/Sidekick#226]
hello,

as title says, sidekick is not terminating old price check msedgewebview2.exe processes.

sidekick version: 3.0.8.5

![image](https://github.com/user-attachments/assets/0b30f1f8-c386-467a-8e37-e3e0519df32d)

**Comment by crosscutsaw** [comment]
sorry for duplicate, i seen it on my second check.

**Comment by leMicin** [comment]
Related to #176
