### ISSUE TITLE
[Feature request] Option to change default value range for affixes

### ISSUE THREAD

**Issue by Wyrade** [Sidekick-Poe/Sidekick#277]
Can you please add a way to change the default affix value change when searching on trade? 
For example, when I tick an affix, by default it searches for 92 life instead of the item's 103 as a minimum. I know some people prefer that way, but an option to change this offset would be nice.
(For example I prefer it to be a 0% offset by default.)

**Comment by leMicin** [comment]
Thanks for the feedback, we're doing this in #310

**Comment by domialex** [comment]
Done in #342
