### ISSUE TITLE
Dps calc ignores elemental dps

### ISSUE THREAD

**Issue by Odelbauer** [Sidekick-Poe/Sidekick#280]
Physical Dps shows as the same as dps even thou there is flat elemental dmg on the weapon.

This seems to happen only when there is also flat added physical dmg on the weapon.
Tested on Quarterstaffs/Warstaffs

Staff with added phys and incorrect calc.
![grafik](https://github.com/user-attachments/assets/a2f31591-4376-4563-bd59-0407b1ac5168)

**Comment by leMicin** [comment]
Fixed in #270
