### ISSUE TITLE
Pricing items from the chat does not work

### ISSUE THREAD

**Issue by Vikerules** [Sidekick-Poe/Sidekick#285]
Tried different keybinds, also turned off wasd movement incase it was interfering with the keybind, cant price check any item from trade.

**Comment by leMicin** [comment]
Are you still experiencing this with the latest version?

**Comment by leMicin** [comment]
I got more reports of this issue occuring

**Comment by domialex** [comment]
Must've been related to the tooltip tags in the items. Can't reproduce.
