### ISSUE TITLE
Using hotkey crashes Path of Exile - sometimes

### ISSUE THREAD

**Issue by ThirteenEra** [Sidekick-Poe/Sidekick#292]
Tried using CTRL+D to check item price, and entire screen went black, followed by Path of Exile crashing. After the crash i could still see Sidekick window, showing the price check for said item

There was no error log or anything so i cant provide more details.

Sidekick was working before (i used it to check a price), since then i closed the game and took a break (PC went into sleep mode), and then when i returned, i launched POE, tried to price check, and game crashed. Im not sure if thats relevant but like i said, i dont have any other helpful info to provide.

Since relaunching POE and Sidekick, no crashes.

**Comment by leMicin** [comment]
We will keep an eye out for similar reports. I don't think we would cause PoE to crash, but we'll see. I will leave this issue opened for a little while.
