### ISSUE TITLE
Exception on Windows shutdown

### ISSUE THREAD

**Issue by leMicin** [Sidekick-Poe/Sidekick#293]
![image](https://github.com/user-attachments/assets/992c1f44-0f85-49af-a6f5-55af9bedb5be)

**Comment by pfeigl** [comment]
Getting the same thing on every shutdown right now

**Comment by domialex** [comment]
HookTask probably needs a CancellationToken when being disposed.

![image](https://github.com/user-attachments/assets/5be41027-4a3d-4ea1-a789-103d074f42ef)
