### ISSUE TITLE
[Bug?] in-game keyboard automatically bind W to Ctrl+C

### ISSUE THREAD

**Issue by deldalus111** [Sidekick-Poe/Sidekick#297]
only occurs when having sidekick open in background then start the game client after. vice versa has no issue.

in-game behavior:
- game will not recognize W as W key but Ctrl+C instead
- in game setting, it still says W (for WASD) but if I re-bind it by pressing W again it will shown as Ctrl+C instead

workaround fix for now
- close game and turn off sidekick. run the game first following by start up sidekick will solves the issue. sidekick still works as intended.

**Comment by leMicin** [comment]
Is this still happening? Reach out on Discord if it is, I would like to explore this
