### ISSUE TITLE
PoE game window focus lost when alt-tabbing during Sidekick price check

### ISSUE THREAD

**Issue by akuznecov** [Sidekick-Poe/Sidekick#300]
**Reproduce steps:**
1. Check price of some item
2. Do not close overlay and switch window to something else
3. Back to the game
4. Try to check price again
5. Hit ESC or "x" on overlay window titlebar to close it
6. You got switched from game to another window

**Short video** explaining the problem (I have added mouse and keyboard overlays into OBS to show what keys are pressed), adjust playback speed in case my actions are too quick for understanding

https://github.com/user-attachments/assets/f494c4be-7bf9-4855-adf4-bb407b11eaed

My video settings, playing on single on monitor right now
![image](https://github.com/user-attachments/assets/d1612ccd-83ad-453c-9a94-c765e937df47)

**Sidekick Beta application version:** 2024.12.17.35
![image](https://github.com/user-attachments/assets/54af4fe4-b618-4bcc-9408-6842d52d3e47)

**Comment by leMicin** [comment]
Fixed in #301 . Feel free to reopen or open a ticket if this isn't fixed in the next release
