### ISSUE TITLE
price check error

### ISSUE THREAD

**Issue by GuanJinsong** [Sidekick-Poe/Sidekick#307]
![PixPin_2024-12-17_20-12-49](https://github.com/user-attachments/assets/f62ea4e1-5519-4f9c-a4c3-8abe8a37267d)
![PixPin_2024-12-17_20-13-57](https://github.com/user-attachments/assets/92e5786d-baa2-4865-8b1e-e770de19fd74)

pls see picture

**Comment by domialex** [comment]
Update to the beta and try this:
![image](https://github.com/user-attachments/assets/9b698011-41fd-4a29-bc14-522e30b9125f)
