### ISSUE TITLE
Enforced ranges on price check

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [Sidekick-Poe/Sidekick#310]
Hello,

liking this so far but I have a few problems

1. Closing the checker-window unfocuses the game or even tabs me to a complete different window
2. Price-Check enforces me, without me wanting that, to a lower range which is extremely bad especially on highest tier rolls that are the minimum value like if Tier X was 100 to 120 life and I have an item with 100, the tool enforces me to search with less than 100 and with that from a lower tier. Even worse are mods with gem levels, if I have a +5 I don't want to search the prices for a +3 or +4. Yes you can "rechange" what value you want to check but it should let me decide to even have that in the first place, this makes the tool for me almost useless as I have to reset all values on each Item all the time

Feature wishes:
1. When Pricechecking an item it would be nice to have a main currency exchange ratio somewhere visible and on hovering it shows each 0.X steps. As we are currently having ex and div as main currency this would be nice do to for those. 
2. When starting up it would be awesome if the tool prechecks in the background (slowly) the most used currencies and their exchange rates to ex, c and div. So if you pricecheck currency it instantly shows you the rough current average price
3. QOL Change: When price checking uniques grey out (still readable) values that can not have different values, highlight important (for price) values, mark values that can change that are not a number value (in poe for example the skill on a replica dragon flight amulet)

I know that some of these are nothing to be expected in a short term but it would be a really great addition. But I hope that at least the 2 problematic points can be fixed soon.

thank you!

**Comment by leMicin** [comment]
Both of these points are covered in different tasks #277 and #300

**Comment by leMicin** [comment]
The exchange rates will be implemented when poe.ninja or another tool computes the value of orbs
