### ISSUE TITLE
Sidekick poe cannot load league data 

### ISSUE THREAD

**Issue by VonKazzas** [Sidekick-Poe/Sidekick#314]
An error occured while trying to get the results from the official trade API. The official trade website may be down. Please try again later or open a ticket on github.
Additional Information: Failed to load league data. 
Someone know how to fix it?

**Comment by leMicin** [comment]
Fixed for now, but we need to improve when cloudflare check is required: https://github.com/Sidekick-Poe/Sidekick/issues/316
