### ISSUE TITLE
Has anyone successfully run Sidekick on Linux using Wine?

### ISSUE THREAD

**Issue by Ali-Hela** [Sidekick-Poe/Sidekick#320]
I've tried many versions of .NET and VC++ but failed. If someone know how or if its doable please share.

**Comment by domialex** [comment]
You will get better support on the discord server. There is a guide to run it on linux, but not through wine.

**Comment by Ali-Hela** [comment]
> You will get better support on the discord server. There is a guide to run it on linux, but not through wine.

Should've checked that first. Thanks for the fast response
