### ISSUE TITLE
Visual Studio 2022's nuget package manager detects two dependencies with known vulnerabilities, these can be updated to mitigate.

### ISSUE THREAD

**Issue by Devlin1991** [Sidekick-Poe/Sidekick#332]
Sidekick\src\Sidekick.Web\Sidekick.Web.csproj : warning NU1904: Package 'System.Text.Encodings.Web' 4.5.0 has a known critical severity vulnerability, https://github.com/advisories/GHSA-ghhp-997w-qr28
Sidekick\src\Sidekick.Wpf\Sidekick.Wpf.csproj : warning NU1903: Package 'System.Private.Uri' 4.3.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-5f2m-466j-3848
Sidekick\src\Sidekick.Wpf\Sidekick.Wpf.csproj : warning NU1902: Package 'System.Private.Uri' 4.3.0 has a known moderate severity vulnerability, https://github.com/advisories/GHSA-x5qj-9vmx-7g6g
Sidekick\src\Sidekick.Wpf\Sidekick.Wpf.csproj : warning NU1903: Package 'System.Private.Uri' 4.3.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-xhfc-gr8f-ffwc
Sidekick\src\Sidekick.Wpf\Sidekick.Wpf.csproj : warning NU1904: Package 'System.Text.Encodings.Web' 4.5.0 has a known critical severity vulnerability, https://github.com/advisories/GHSA-ghhp-997w-qr28

System.Private.Uri can be updated to 4.3.2 
System.Text.Encodings.Web can be updated to 4.5.1

![image](https://github.com/user-attachments/assets/4708dbfb-b3b9-4fed-a028-6c0762765beb)
![image](https://github.com/user-attachments/assets/241184bb-decd-43e4-a4f0-b385c6644c91)

**Comment by domialex** [comment]
Thanks, we'll update those packages.
