### ISSUE TITLE
[Bug] Uncut gems search is broken

### ISSUE THREAD

**Issue by akuznecov** [Sidekick-Poe/Sidekick#348]
Lookup over any uncut gem type leads to unexpected search results - wrong items present in output

![image](https://github.com/user-attachments/assets/cc60a8b1-c49f-46ab-99ec-c9b0261cb694)
![image](https://github.com/user-attachments/assets/b6da52e5-7003-4be2-b2ef-e2b98a18576c)
![image](https://github.com/user-attachments/assets/32fcc5e9-eb23-4548-b0d3-16e56ac8d109)

**Comment by leMicin** [comment]
Fixed in #382
