### ISSUE TITLE
[Bug] Error screen on price check

### ISSUE THREAD

**Issue by agonzalezdev** [Sidekick-Poe/Sidekick#349]
Since a few days ago, whenever I try to check a price I get this error (and yes, the web is working when I try it).
As now they have added many more layers of security (cloudflare, login every X minutes, etc...) maybe it something related to this.

![image](https://github.com/user-attachments/assets/0829c333-cac0-4f93-82b6-918ae0116fb1)

**Comment by leMicin** [comment]
Can you reach out on Discord, or send me logs that are located in %appdata%/sidekick?

**Comment by agonzalezdev** [comment]
> Can you reach out on Discord, or send me logs that are located in %appdata%/sidekick?

NVM! I removed all the content on this folder and now it works like a charm. Thank you!

**Comment by agonzalezdev** [comment]
[Sidekick_log20241220.log](https://github.com/user-attachments/files/18214757/Sidekick_log20241220.log)

It failed again, so i re-open this. Almost sure that if i delete all the folder again will work again. But just in case i send the logs

**Comment by agonzalezdev** [comment]
I confirm that it always fixes if I delete AppData, it must be that it enters an inconsistent state the first time it fails and does not retry the connection, but tries to reuse the one it already has.

**Comment by ztw07** [comment]
same problem 
[Sidekick_log20241220.log](https://github.com/user-attachments/files/18215096/Sidekick_log20241220.log)

**Comment by ztw07** [comment]
I've solved it. I set the league type in the settings and everything worked. This is my mistake, sry

**Comment by domialex** [comment]
Seems to be a league mismatch in the settings.
