### ISSUE TITLE
Freesync / Gsync not working while sidekick is running

### ISSUE THREAD

**Issue by aLanaMaunz** [Sidekick-Poe/Sidekick#351]
Hello,
due to the overlay, Gsync/Freesync is not working. Other overlays got a "-noOverlay" launchparameter, which is forcing them to display all data in a webbrowser. Is this possible for sidekick too?

**Comment by domialex** [comment]
There is no permanent overlay with Sidekick, it opens the price-check on demand. I'm not sure what kind of behavior you are getting with gsync. Can you describe it with more details?

**Comment by Davidson-Mike** [comment]
> (Does PoE2 even have gsync support?)

@domialex Gsync isn't supported at a software level - it's a hardware implementation. All software running on gsync capable hardware has gsync support. So the answer would be yes - given appropriate hardware to run Gsync.

@aLanaMaunz please make sure you are running the game in fullscreen. Gsync natively only applies to fullscreen applications. You can adjust this behavior in Nvidia Control Panel to work on windowed applications as well but I'd caution against it as it causes other issues. Generally, if you want gsync to work; run fullscreen. Also ensure it is active and working according to Nvidia Control Panel.

**Comment by aLanaMaunz** [comment]
Thanks!
Switching to fullscreen-only solved the issue completely for me. No idea why there is a problem with window-mode and (in my case) Gsync but this solution is perfectly fine for me.

I used my monitors OSD to display the current refresh rate in realtime. This rate should match the POE2 FPS - else the sync is not working.

My observations:
POE2 in window mode - even closing sidekick completely doesn't bring back Gsync to a working state. Only changing the resolution ingame or restarting the game fixes the problem. Looks like Gsync is switching to syncing the sidekick overlay but can't go back to syncing POE if the overlay is closed. Tabbing / Minimizing / etc won't help.

POE2 in fullscreen mode - working as expected. Gsync stays on and is syncing the game FPS while ignoring the overlay rendering.
