### ISSUE TITLE
Add option to set custom divine/ex ratio

### ISSUE THREAD

**Issue by Xebtria** [Sidekick-Poe/Sidekick#368]
currently the tool apparently assumes that divines are roughly 1:4 ex or so, because I have many items that are listed by 1ex, 2ex, 3ex and then suddenly items with a divine appear. sometimes it takes many many "show more results" and then some items with 7 ex, 10ex etc start appearing.

would be nice to have the option to set a custom divine ratio in the options somewhere, and then have the search results sorted having this ratio in mind. 

would this be possible?

or, alternatively, if it isn't possible due to whatever technical or API limitations, give me an option so I see **only** results for Exalteds or **only** results for divines. on the website this is possible by selecting the specific buyout currency: 
![](https://i.imgur.com/5Wx0V7Q.png)

**Comment by domialex** [comment]
The tool does not assume the ratios of the currencies, that is handled by the official trade depending on what currency you are searching with.
In the settings you can choose which currency to use, just like the official trade.
![image](https://github.com/user-attachments/assets/01c62ad9-9f89-4e91-b809-dfd773343bc7)
The "Relative" option is probably the same thing as  "Chaos Orb Equivalent" from PoE1.
