### ISSUE TITLE
Sidekick not opening

### ISSUE THREAD

**Issue by parqual** [Sidekick-Poe/Sidekick#383]
The Sidekick program is not opening on my PC. I recently installed a new Windows 10, and after that, I removed some Windows components (such as Microsoft Edge) from the newly installed operating system. It was working fine on the previous operating system. I am attaching the log file here.
[Sidekick_log20241224.log](https://github.com/user-attachments/files/18235787/Sidekick_log20241224.log)

**Comment by leMicin** [comment]
Make sure you read through the troubleshooting steps on our website: https://sidekick-poe.github.io/#troubleshooting
WebView2 (edge) is a required dependency.

**Comment by parqual** [comment]
I was getting an error while installing WebView2, and after researching the issue a bit, I fixed it. Let me write the solution here for those who encounter the WebView2 issue:

Run PowerShell as Administrator;

winget install --id=Microsoft.EdgeWebView2Runtime -e

Then complete the installation. I solved the issue this way. Good luck!
