### ISSUE TITLE
Sidekick failed to communicate with the API

### ISSUE THREAD

**Issue by criticallyblunt** [Sidekick-Poe/Sidekick#385]
I just downloaded the new sidekick that was released about 20 min ago. Every time I open the application, it just says Sidekick failed to communicate with the API. The only option I get is to exit the application.
![sidekick](https://github.com/user-attachments/assets/6e6b1f61-e327-4734-b3c0-f772a5db70b0)

**Comment by criticallyblunt** [comment]
I can access the trade website fine, so that is not the issue.

**Comment by leMicin** [comment]
Can you share your logs located at %appdata%/sidekick

**Comment by criticallyblunt** [comment]
I deleted the directory, relaunched the application and now it works. Thank you!
