### ISSUE TITLE
Recent update, Not working

### ISSUE THREAD

**Issue by NaylaInsan3** [Sidekick-Poe/Sidekick#386]
Recently updated App and i now cannot load the app when trying to search through ingame
All i get is this message when i try to search for something
![image](https://github.com/user-attachments/assets/926727bc-bddc-4d55-83ea-34ab4d1a41e7)

**Comment by domialex** [comment]
You can try reinstall completely. You'll need to also delete the `%appdata%/sidekick` folder.

**Comment by NaylaInsan3** [comment]
> You can try reinstall completely. You'll need to also delete the `%appdata%/sidekick` folder.

I have reinstalled, and deleteed everything in the %appdata%/Sidekick folder and still having the same issue

**Comment by NaylaInsan3** [comment]
[Sidekick_log20241224.log](https://github.com/user-attachments/files/18245654/Sidekick_log20241224.log)

**Comment by leMicin** [comment]
Maybe fixed in #392 
We are releasing the fix soon. After the release, can you try again?

**Comment by NaylaInsan3** [comment]
After the recent update release it is now working again.
Thankyou for the quick responses.
