### ISSUE TITLE
High CPU-Usage - even when the Game is not running

### ISSUE THREAD

**Issue by FreakErn** [Sidekick-Poe/Sidekick#387]
When i start the Sidekick Beta (and in the non-beta version), the App is constantly using 10-20% of my cpu, even when POE2 is not even running.
I have not changed any settings, the app has default settings.

I am running a AMD Ryzen 7500F. What is the app doing there? 
I hope you are not running a loop for checking if the shortcut is pressed, are you?

**Comment by taboo9** [comment]
I hope they are not crypto mining, are they?

**Comment by VincentWillats** [comment]
Yup, the performance since I updated to 2024.12.24.452 has been terrible. Constantly having to close and reopen it.

I have seen it idle at 20-30% cpu usage too.

**Comment by FreakErn** [comment]
> I hope they are not crypto mining, are they?

From what I have seen is, they are respawning threads, I don‘t know why, but it does not look like they are mining… but I could be wrong 🤪

**Comment by BK-Morpheus** [comment]
I swapped from beta to release version yesterday because I noticed that sidekick beta+msedgewebview2.exe are causing high CPU load (around 10-15% total CPU load on a 8 core/16 thread machine).
Now this "bug" is in the newest release version as well.

**Comment by gwendolynemaxinegwenstacy** [comment]
Freezing and have to use task manager to close it every hour.

**Comment by domialex** [comment]
It's a memory leak somewhere in the code, and from a recent change. We'll look into it.
