### ISSUE TITLE
No Build Instructions

### ISSUE THREAD

**Issue by MrGranddy** [Sidekick-Poe/Sidekick#388]
It is not common practice for an "open-source" project to aggressively encourage people to download a pre-compiled binary instead of providing building instructions. This is the main reason for the doubt about this project. Please provide build instructions so anyone with suspicions of the released binaries can compile the app themselves.

**Comment by KewkLW** [comment]
Steps to build 

1. Clone project. 
2. Open Visual Studio 2022. 
3. Load Sidekick.sln from the cloned dir. 
4. ctrl+shift+b to build the project.

**Comment by domialex** [comment]
Like @KewkLW suggested, it's really straightforward.
The binaries are directly built from the source with GitHub Actions:
https://github.com/Sidekick-Poe/Sidekick/tree/main/.github/workflows

You can run the code from dotnet cli, vscode or vs2022. **You need dotnetsdk and npm for the stylesheets**.

I will add a mention on the readme.
