### ISSUE TITLE
Unable to parse Item in inactive weapon slot

### ISSUE THREAD

**Issue by sp117f** [Sidekick-Poe/Sidekick#423]
I tried to CTRL+D while this item was not on my active weapon slot.  I cannot parse even when I put the item in the inventory from the inactive weapon slot.  I have to put the item in an active slot before the issue fixes itself and allows for parsing again.

![image](https://github.com/user-attachments/assets/abeb583e-b726-44e7-b089-00953c74e53e)

**Comment by leMicin** [comment]
Duplicate of #278
