### ISSUE TITLE
[Ui] Add setting to disable init splash view

### ISSUE THREAD

**Issue by domialex** [Sidekick-Poe/Sidekick#442]
If there's no error and/or update, the view could stay hidden with a setting.

**Comment by leMicin** [comment]
I agree that the view is annoying, though having nothing happen at all could be more misleading than not. I think I'd prefer if we somehow removed all "Modal" type views and only kept Standard and overlay views. The update/initialization/setup process in the beginning would then use standard views, which can be put behind other applications and they appear in the task bar to bring them back in focus.
