### ISSUE TITLE
Conflict with Sidekick browser

### ISSUE THREAD

**Issue by xactfoxy** [Sidekick-Poe/Sidekick#447]
Just an FYI the latest updated which removed the old client also removed my browser of choice also named Sidekick along with all my settings, history and bookmarks.

**Comment by domialex** [comment]
I tested it and can confirm that this does happen, what a weird interaction. I'll try to see with the library of the installer we use if it's a known bug.

For now you can use the portable version of Sidekick, it also auto-updates.
